eureka:
  client:
    service-url:
      defaultZone: http://eureka:123456@localhost:8761/eureka
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}

spring:
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9411
    
server:
  tomcat:
    accept-count: 20
    max-connections: 80
    min-spare-threads: 5
    max-threads: 20
    
    basedir: .
    accesslog:
      enabled: true
      pattern: '%{X-Forwarded-For}i %a %t %{X-B3-TraceId}i %m %U %s %b %D'

