eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://eureka:123456@localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}

spring:
  sleuth:
    sampler:
      percentage: 0.1
  zipkin:
    locator:
      discovery:
        enabled: true
    base-url: http://zipkin-server

server:
  tomcat:
    accept-count: 20
    max-connections: 80
    min-spare-threads: 5
    max-threads: 20
    
    basedir: .
    accesslog:
      enabled: true
      pattern: '%{X-Forwarded-For}i %a %t %{X-B3-TraceId}i %m %U %s %b %D'

