spring:
  application:
    name: user-provider

info:
  service.name: ${spring.application.name}
  service.ower: SaaS/dinstone@163.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

server:
  port: 7000
 
management: 
  port: 7001
  security: 
    enabled: false
