spring:
  application:
    name: user-consumer
    
info:
  service.name: ${spring.application.name}
  service.ower: SaaS/dinstone@163.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
server:
  port: 8080

management: 
  port: 8081
  security: 
    enabled: false

feign:
  hystrix: 
    enabled: true