spring:
  application: 
    name: gatway-zuul

info:
  service:
    name: ${spring.application.name}
    ower: SaaS/dinstone@163.com
  build:
    group: "@project.groupId@"
    artifact: "@project.artifactId@"
    version: "@project.version@"
    description: "@project.description@"
  
server:
  port: 9000

security:
  basic:
    enabled: false
  user: 
    name: zuul
    password: 123456

management: 
  port: 9001
  security: 
    enabled: false
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka:123456@localhost:8761/eureka
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}

zuul:
  ignored-services: "*"
  routes: 
    user-provider: /up/**
    user-consumer: /uc/**

---
spring:
  profiles: dev,default
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    locator:
      discovery:
        enabled: true
    base-url: http://zipkin-server
  
    