spring:
  application: 
    name: zipkin-server

info:
  service:
    name: ${spring.application.name}
    ower: SaaS/dinstone@163.com
  build:
    group: "@project.groupId@"
    artifact: "@project.artifactId@"
    version: "@project.version@"
    description: "@project.description@"
  
server:
  port: 9411

security:
  basic:
    enabled: false

management: 
  port: 9410
  security: 
    enabled: false
