spring:
  application: 
    name: vertx-service
  main:
    web-environment: false

info:
  service:
    name: ${spring.application.name}
    ower: SaaS/dinstone@163.com
  build:
    group: "@project.groupId@"
    artifact: "@project.artifactId@"
    version: "@project.version@"
    description: "@project.description@"

eureka:
  client:
    service-url:
      defaultZone: http://eureka:123456@localhost:8761/eureka
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}

---
spring:
  profiles: default,i1

server:
  port: 8180

management: 
  port: 8181
  security: 
    enabled: false

vertx:
  rest:
    port: ${server.port}
    
---
spring:
  profiles: i2

server:
  port: 8280

management: 
  port: 8281
  security: 
    enabled: false

vertx:
  rest:
    port: ${server.port}
