spring:
   application:
      name: cloud-gatway
   security:
      user:
         name: apm
         password: 123456
   sleuth:
      sampler:
         percentage: 0.1
   zipkin:
      locator:
         discovery:
            enabled: true
      base-url: http://127.0.0.1:9411
   cloud:
      loadbalancer:
         ribbon:
            enabled: false
      consul:
         discovery:
            # 启用服务发现
            enabled: true
            # 启用服务注册
            register: true
            # 服务停止时取消注册
            deregister: true
            # 表示注册时使用IP而不是hostname
            prefer-ip-address: true
            # 执行监控检查的频率
            health-check-interval: 10s
            # 设置健康检查失败多长时间后，取消注册
            health-check-critical-timeout: 30s
            # 服务注册标识，格式为：应用名称+服务器IP+端口
            instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
      gateway:
         discovery:
            locator:
               enabled: false
               lower-case-service-id: true
         routes:
            - id: service_consumer
              uri: lb://user-consumer
              predicates:
                 - Path=/uc/**
              filters:
                 - StripPrefix=1
            - id: service_provider
              uri: lb://user-provider
              predicates:
                 - Path=/up/**
              filters:
                 - StripPrefix=1
            - id: service_config
              uri: http://localhost:8080
              predicates:
                 - Path=/cc/**
              filters:
                 - StripPrefix=1
server:
   port: 4444
management:
   server:
      port: 4445
   endpoints:
      web:
         exposure:
            include: "*"
         cors:
            allowed-origins: http://example.com
            allowed-methods: GET,POST

---
spring:
   profiles: default
   cloud:
      consul:
         host: 192.168.1.120
         port: 8500
      config:
         fail-fast: true
         uri: http://localhost:8888/
         profile: default
         label: offline
---
spring:
   profiles: online
   cloud:
      consul:
         host: consul-service
         port: 8500
      config:
         fail-fast: true
         uri: http://config-service:8888/
         profile: default
         label: online
