spring:
   application:
      name: cloud-gatway
   security:
      user:
         name: apm
         password: 123456
   cloud:
      gateway:
         discovery:
            locator:
               enabled: true
               lower-case-service-id: true
         routes:
         - id: service_consumer
           uri: lb://user-consumer
           predicates:
           - Path=/uc/**
           filters:
           - StripPrefix=1
           
info:
   service:
      name: ${spring.application.name}
      ower: SaaS/dinstone@163.com
   build:
      group: '@project.groupId@'
      artifact: '@project.artifactId@'
      version: '@project.version@'
      description: '@project.description@'
server:
   port: 4444
management:
   server:
      port: 4445
   endpoints:
      web:
         exposure:
            include: '*'
         cors:
            allowed-origins: http://example.com
            allowed-methods: GET,POST
eureka:
   client:
      service-url:
         defaultZone: http://eureka:123456@localhost:8761/eureka
   instance:
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
---
spring:
   profiles: dev,default
   sleuth:
      sampler:
         percentage: 1.0
   zipkin:
      locator:
         discovery:
            enabled: true
      base-url: http://127.0.0.1:9411