spring:
  application: 
    name: eureka-server
    
info:
  service:
    name: ${spring.application.name}
    ower: SaaS/dinstone@163.com
  build:
    group: "@project.groupId@"
    artifact: "@project.artifactId@"
    version: "@project.version@"
    description: "@project.description@"

server:
  port: 8761

management: 
  port: 8760
  security: 
    enabled: false
    
security:
  basic:
    enabled: true
  user:
    name: eureka
    password: 123456

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka:123456@localhost:8761/eureka
  server:
    response-cache-auto-expiration-in-seconds: 180 
    response-cache-update-interval-ms: 3000
    eviction-interval-timer-in-ms: 3000
    
