spring:
  application: 
    name: eureka-server
    
info:
  service.name: ${spring.application.name}
  service.ower: IaaS/dinstone@163.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

server:
  port: 8761

management: 
  port: 8760
  security: 
    enabled: false
    
security:
  basic:
    enabled: true
  user:
    name: eureka
    password: 123456

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka:123456@localhost:8761/eureka
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
