spring:
   application:
      name: apm-admin
   security:
      basic:
         enabled: false
      user:
         name: apm
         password: 123456
info:
   service:
      name: ${spring.application.name}
   owner:
      name: PaaS/dinstone
      email: dinstone@163.com
   build:
      group: '@project.groupId@'
      artifact: '@project.artifactId@'
      version: '@project.version@'
      description: '@project.description@'
server:
   port: 9999
management:
   port: 9998
   security:
      enabled: false
eureka:
   client:
      register-with-eureka: false
      service-url:
         defaultZone: http://eureka:123456@localhost:8761/eureka
   instance:
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}