spring:
   application:
      name: apm-admin
   security:
      basic:
         enabled: false
      user:
         name: apm
         password: 123456
   cloud:
     consul:
       discovery:
         register: false

server:
   port: 9999

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

---
spring:
  profiles: default
  cloud:
    consul:
      host: 192.168.1.120
      port: 8500

---
spring:
  profiles: online
  cloud:
    consul:
      host: consul-service
      port: 8500
