spring:
  application:
    name: config-server
info:
  service:
    name: ${spring.application.name}
    owner:
      name: dinstone
      email: dinstone@163.com
  build:
    group: '@project.groupId@'
    artifact: '@project.artifactId@'
    version: '@project.version@'
    description: '@project.description@'
server:
  port: 8888
management:
   server:
      port: 8889
      security:
         enabled: false
eureka:
  client:
    enabled: false